spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BDDNA
    username: postgres
    password: rjex73g1-
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      generate-ddl: true
    show-sql: true            
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true