spring:
  main:    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/BDDNA
    username: postgres
    password: rjex73g1-
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false      
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true