spring:
  main:    lazy-initialization: true
  datasource:
    url: ${DS_URL}
    username: ${DS_USER}
    password: ${DS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false      
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
logging:  level:    web: error            